-- | Public API re-exports for building and computing flex layouts.
module Flexy
  ( Node
  , LayoutNode
  , Style
  , Layout
  , Size(..)
  , Value(..)
  , Dimension(..)
  , Align(..)
  , Justify(..)
  , FlexDirection(..)
  , FlexWrap(..)
  , PositionType(..)
  , BoxSizing(..)
  , Overflow(..)
  , WritingMode(..)
  , Direction(..)
  , MeasureFunc
  , BaselineFunc
  , LayoutConfig(..)
  , defaultConfig
  , defaultStyle
  , node
  , withChildren
  , withMeasure
  , withBaseline
  , withKey
  , layoutBounds
  , layoutChildren
  , layoutKey
  , setSize
  , setWidth
  , setHeight
  , setMinWidth
  , setMinHeight
  , setMaxWidth
  , setMaxHeight
  , setFlexDirection
  , setFlexWrap
  , setJustifyContent
  , setAlignItems
  , setAlignSelf
  , setAlignContent
  , setFlexGrow
  , setFlexShrink
  , setFlexBasis
  , setPositionType
  , setOrder
  , setAspectRatio
  , setBoxSizing
  , setOverflow
  , setWritingMode
  , setFlex
  , setFlexFlow
  , setGaps
  , setDirection
  , setPaddingAll
  , setPaddingLTRB
  , setMarginAll
  , setMarginLTRB
  , setMarginLR
  , setBorderAll
  , setBorderStartEnd
  , setPositionLTRB
  , computeLayout
  ) where

import Flexy.Config (LayoutConfig(..), defaultConfig)
import Flexy.Layout (Layout, LayoutNode, computeLayout, layoutBounds, layoutChildren, layoutKey)
import Flexy.Measure (MeasureFunc, BaselineFunc)
import Flexy.Node (Node, node, withChildren, withMeasure, withBaseline, withKey)
import Flexy.Style
  ( Style
  , defaultStyle
  , setSize
  , setWidth
  , setHeight
  , setMinWidth
  , setMinHeight
  , setMaxWidth
  , setMaxHeight
  , setFlexDirection
  , setFlexWrap
  , setJustifyContent
  , setAlignItems
  , setAlignSelf
  , setAlignContent
  , setFlexGrow
  , setFlexShrink
  , setFlexBasis
  , setPositionType
  , setOrder
  , setAspectRatio
  , setBoxSizing
  , setOverflow
  , setWritingMode
  , setFlex
  , setFlexFlow
  , setGaps
  , setDirection
  , setPaddingAll
  , setPaddingLTRB
  , setMarginAll
  , setMarginLTRB
  , setMarginLR
  , setBorderAll
  , setBorderStartEnd
  , setPositionLTRB
  )
import Flexy.Types
  ( Size(..)
  , Value(..)
  , Dimension(..)
  , Align(..)
  , Justify(..)
  , FlexDirection(..)
  , FlexWrap(..)
  , PositionType(..)
  , BoxSizing(..)
  , Overflow(..)
  , WritingMode(..)
  , Direction(..)
  )
